site_name: SGES
site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01-SGES/
repo_url: https://github.com/mdsreq-fga-unb/REQ-2026.1-T01-SGES
repo_name: mdsreq-fga-unb/REQ-2026.1-T01-SGES

theme:
  name: material
  language: pt-BR
  palette:
    # Ativa o Tema Claro por padrão
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para tema escuro
    # Ativa o Tema Escuro
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para tema claro

  font:
    text: Source Sans 3
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:Print ou link de boards (ex: Miro/Trello) utilizados durante a dinâmica.
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.tabs.link


nav:
  - "Início": index.md
  - "Visão do Produto e Projeto":
      - "Visão do Projeto": "visao_projeto.md"
      - "Cenário Atual e Negócio": "cenario_atual_e_negocio.md"
      - "Solução Proposta": "solucao_proposta.md"
      
  - "Engenharia de Software":
      - "Estratégias de Eng. de Software": "estrategias_eng_software.md"
      - "Interação Equipe e Cliente": "interacao_equipe_cliente.md"
      - "Engenharia de Requisitos": "engenharia_requisitos.md"

  - "Gestão de Produto":
      - "Lista de Requisitos": "lista_requisitos.md"
      - "Catálogo de Regras de Negócio": "catalogo_regras_negocio.md"
      - "Itens de Trabalho e priorização": "matriz_de_acao_e_priorizacao.md"
      - "Arquitetura do Produto": "arquitetura_do_produto.md"
      - "Casos de Uso":
          - "CSU01":
            - "fluxo": ./lista_trabalhos/csu01/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu01/DoR_DoD.md
          - "CSU02":
            - "fluxo": ./lista_trabalhos/csu02/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu02/DoR_DoD.md
          - "CSU03":
            - "fluxo": ./lista_trabalhos/csu03/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu03/DoR_DoD.md
          - "CSU04":
            - "fluxo": ./lista_trabalhos/csu04/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu04/DoR_DoD.md
          - "CSU05":
            - "fluxo": ./lista_trabalhos/csu05/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu05/DoR_DoD.md
          - "CSU06":
            - "fluxo": ./lista_trabalhos/csu06/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu06/DoR_DoD.md
          - "CSU07":
            - "fluxo": ./lista_trabalhos/csu07/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu07/DoR_DoD.md
          - "CSU08":
            - "fluxo": ./lista_trabalhos/csu08/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu08/DoR_DoD.md
          - "CSU09":
            - "fluxo": ./lista_trabalhos/csu09/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu09/DoR_DoD.md
          - "CSU10":
            - "fluxo": ./lista_trabalhos/csu10/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu10/DoR_DoD.md
          - "CSU11":
            - "fluxo": ./lista_trabalhos/csu11/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu11/DoR_DoD.md
          - "CSU12":
            - "fluxo": ./lista_trabalhos/csu12/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu12/DoR_DoD.md
          - "CSU13":
            - "fluxo": ./lista_trabalhos/csu13/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu13/DoR_DoD.md
          - "CSU14":
            - "fluxo": ./lista_trabalhos/csu14/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu14/DoR_DoD.md
          - "CSU15":
            - "fluxo": ./lista_trabalhos/csu15/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu15/DoR_DoD.md
          - "CSU16":
            - "fluxo": ./lista_trabalhos/csu16/fluxo.md
            - "DoR & DoD": ./lista_trabalhos/csu16/DoR_DoD.md

  - "Acompanhamento do Projeto":
      - "Planejamento e Organização":
        - "Planejamento": planejamento_organizacao/cronograma_e_entregas.md
        - "Rastreabilidade": planejamento_organizacao/rastreabilidade.md
        - "Quadro MVP": planejamento_organizacao/quadro_mvp.md

      - "Gravações das unidades":
          - "Vídeo da Unidade 1": unidade_1_video.md
          - "Vídeo da Unidade 2": unidade_2_video.md
          - "Vídeo da Unidade 3": unidade_3_video.md
          - "Vídeo da Unidade 4": unidade_4_video.md
          
      - "Reunião com a cliente":
        - "Ata da Reunião de Validação do Escopo e Objetivos": reuniao_de_alinhamento.md
        - "Ata da Reunião de Validação de Requisitos": reuniao_de_requisitos.md
        - "Vídeo de Apresentação do MVP": validacao_unidade_3.md

      - "Atas":
        - "Atas de Planos de Iteração":
          - "Ata de plano de iteração da concepção": atas/atas_planos_iteracao/ata_plano_iteracao_concepcao.md
          - "Ata de plano de iteração da elaboração": atas/atas_planos_iteracao/ata_plano_iteracao_elaboracao.md
          - "Ata de plano de iteração da construção 1": atas/atas_planos_iteracao/ata_plano_iteracao_construcao1.md
          - "Ata de plano de iteração da construção 2": atas/atas_planos_iteracao/ata_plano_iteracao_construcao2.md
          - "Ata de plano de iteração da transição": atas/atas_planos_iteracao/ata_plano_iteracao_transicao.md

      - "Evidências de ER e EW":
        - "1. Concepção": paginas_de_evidencia/evidencias_concepcao.md
        - "2. Elaboração": paginas_de_evidencia/evidencias_elaboracao.md  
        - "3. Construção 1": paginas_de_evidencia/evidencias_construcao_iteracao1.md  
        - "4. Construção 2": paginas_de_evidencia/evidencias_construcao_iteracao2.md
        - "5. Transição": paginas_de_evidencia/evidencias_transicao.md
        - "Áudio referente a Reunião - 1 Iteração": audio_reuniao.md
      - "Lições Aprendidas": "iteracao/licoes_aprendidas.md"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
