site_name: SGES
site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01-SGES/
repo_url: https://github.com/mdsreq-fga-unb/REQ-2026.1-T01-SGES
repo_name: mdsreq-fga-unb/REQ-2026.1-T01-SGES

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
  font:
    text: Source Sans 3
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.tabs.link

nav:
  - "Início": index.md
  - "Visão do Produto e Projeto":
      - "Visão do Projeto": "visao_projeto.md"
      - "1. Cenário Atual e Negócio": "cenario_atual_e_negocio.md"
      - "2. Solução Proposta": "solucao_proposta.md"
      - "3. Estratégias de Eng. de Software": "estrategias_eng_software.md"
      - "4. Engenharia de Requisitos": "engenharia_requisitos.md"
      - "5. Lista de Requisitos": "lista_requisitos.md"
      - "6. Matriz de Ação e Priorização": "matriz_de_acao_e_priorizacao.md"
      - "7. Cronograma e Entregas": "cronograma_e_entregas.md"
      - "8. Interação Equipe e Cliente": "interacao_equipe_cliente.md"
  - "Atas e Gravações das Sprints":
      - "Vídeo da Unidade 1": unidade_1_video.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
